import io
import logging
from datetime import datetime, timezone, timedelta

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, Image,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

from analytics.engine import (
    dataset_summary, column_analysis, correlation_matrix, outlier_detection,
    distribution_data, scatter_data, box_plot_data,
)

logger = logging.getLogger("dataforge.analytics.report")

BRAND = "DataForgeAI"
WATERMARK_COLOR = colors.Color(0.85, 0.85, 0.92, alpha=0.35)
BRAND_PURPLE = "#7c3aed"
BRAND_INDIGO = "#4f46e5"
BRAND_VIOLET_LIGHT = "#ede9fe"
CHART_PALETTE = ["#7c3aed", "#4f46e5", "#06b6d4", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#ec4899"]

# Common chart dimensions
CHART_W = 5.8  # inches
CHART_H = 3.2  # inches
SMALL_CHART_W = 4.5
SMALL_CHART_H = 2.8


def _watermark(canvas, doc):
    """Draw diagonal watermark + footer on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 52)
    canvas.setFillColor(WATERMARK_COLOR)
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(35)
    canvas.drawCentredString(0, 0, BRAND)
    canvas.restoreState()

    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.Color(0.5, 0.5, 0.5))
    canvas.drawString(30 * mm, 12 * mm, f"Generated by {BRAND}")
    canvas.drawRightString(A4[0] - 30 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Chart rendering helpers (matplotlib → PNG bytes → ReportLab Image)
# ---------------------------------------------------------------------------

def _fig_to_image(fig, width=CHART_W, height=CHART_H) -> Image:
    """Convert a matplotlib figure to a ReportLab Image flowable."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight", facecolor="white", edgecolor="none")
    plt.close(fig)
    buf.seek(0)
    return Image(buf, width=width * inch, height=height * inch)


def _style_ax(ax, title="", xlabel="", ylabel=""):
    """Apply consistent styling to axes."""
    ax.set_title(title, fontsize=11, fontweight="bold", color="#1f2937", pad=10)
    ax.set_xlabel(xlabel, fontsize=9, color="#4b5563")
    ax.set_ylabel(ylabel, fontsize=9, color="#4b5563")
    ax.tick_params(labelsize=8, colors="#6b7280")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#d1d5db")
    ax.spines["bottom"].set_color("#d1d5db")
    ax.grid(axis="y", alpha=0.3, color="#9ca3af")


def _draw_histogram(series: pd.Series, col_name: str, bins: int = 25) -> Image:
    fig, ax = plt.subplots(figsize=(CHART_W, CHART_H))
    ax.hist(series.dropna(), bins=bins, color=BRAND_PURPLE, alpha=0.8, edgecolor="white", linewidth=0.5)
    _style_ax(ax, title=f"Distribution — {col_name}", xlabel=col_name, ylabel="Frequency")
    fig.tight_layout()
    return _fig_to_image(fig)


def _draw_bar_chart(labels: list, counts: list, col_name: str) -> Image:
    fig, ax = plt.subplots(figsize=(CHART_W, CHART_H))
    short_labels = [str(l)[:18] for l in labels]
    bars = ax.barh(short_labels[::-1], counts[::-1], color=CHART_PALETTE[:len(labels)], edgecolor="white", linewidth=0.5)
    _style_ax(ax, title=f"Top Values — {col_name}", xlabel="Count", ylabel="")
    fig.tight_layout()
    return _fig_to_image(fig)


def _draw_scatter(df: pd.DataFrame, col_x: str, col_y: str) -> Image:
    fig, ax = plt.subplots(figsize=(CHART_W, CHART_H))
    sample = df[[col_x, col_y]].dropna()
    if len(sample) > 500:
        sample = sample.sample(500, random_state=42)
    ax.scatter(sample[col_x], sample[col_y], alpha=0.5, s=18, color=BRAND_PURPLE, edgecolors="white", linewidth=0.3)
    _style_ax(ax, title=f"Scatter — {col_x} vs {col_y}", xlabel=col_x, ylabel=col_y)
    fig.tight_layout()
    return _fig_to_image(fig)


def _draw_heatmap(corr_dict: dict) -> Image:
    cols = corr_dict["columns"]
    matrix = np.array(corr_dict["matrix"])
    fig, ax = plt.subplots(figsize=(min(CHART_W + 1, 7), min(CHART_H + 1, 5)))
    cmap = sns.diverging_palette(260, 20, as_cmap=True)
    sns.heatmap(
        matrix, annot=True, fmt=".2f", cmap=cmap,
        xticklabels=cols, yticklabels=cols,
        center=0, vmin=-1, vmax=1, linewidths=0.5, linecolor="white",
        ax=ax, cbar_kws={"shrink": 0.8},
        annot_kws={"size": 7},
    )
    ax.set_title("Correlation Heatmap", fontsize=12, fontweight="bold", color="#1f2937", pad=12)
    ax.tick_params(labelsize=7)
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")
    fig.tight_layout()
    return _fig_to_image(fig, width=min(CHART_W + 1, 7), height=min(CHART_H + 1, 5))


def _draw_boxplot(df: pd.DataFrame, columns: list[str]) -> Image:
    fig, ax = plt.subplots(figsize=(CHART_W, CHART_H))
    data_to_plot = [df[c].dropna().values for c in columns]
    bp = ax.boxplot(
        data_to_plot, labels=[c[:15] for c in columns], patch_artist=True,
        boxprops=dict(facecolor=BRAND_VIOLET_LIGHT, edgecolor=BRAND_PURPLE, linewidth=1),
        medianprops=dict(color="#dc2626", linewidth=1.5),
        whiskerprops=dict(color=BRAND_PURPLE, linewidth=1),
        capprops=dict(color=BRAND_PURPLE, linewidth=1),
        flierprops=dict(marker="o", markersize=3, markerfacecolor="#f59e0b", markeredgecolor="#f59e0b", alpha=0.6),
    )
    _style_ax(ax, title="Box Plot — Numeric Columns", xlabel="", ylabel="Value")
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    fig.tight_layout()
    return _fig_to_image(fig)


def _draw_pie(labels: list, values: list, col_name: str) -> Image:
    fig, ax = plt.subplots(figsize=(SMALL_CHART_W, SMALL_CHART_H))
    clrs = CHART_PALETTE[:len(labels)]
    wedges, texts, autotexts = ax.pie(
        values, labels=None, autopct="%1.1f%%", startangle=90, colors=clrs,
        pctdistance=0.8, textprops={"fontsize": 7},
    )
    ax.legend(
        wedges, [str(l)[:20] for l in labels],
        loc="center left", bbox_to_anchor=(1.0, 0.5), fontsize=7, frameon=False,
    )
    ax.set_title(f"Distribution — {col_name}", fontsize=10, fontweight="bold", color="#1f2937")
    fig.tight_layout()
    return _fig_to_image(fig, width=SMALL_CHART_W, height=SMALL_CHART_H)


# ---------------------------------------------------------------------------
# PDF generation
# ---------------------------------------------------------------------------

def generate_pdf(df: pd.DataFrame, filename: str, file_size: int) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=25 * mm, bottomMargin=25 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("BrandTitle", parent=styles["Title"], fontSize=22, textColor=colors.HexColor(BRAND_PURPLE), spaceAfter=6))
    styles.add(ParagraphStyle("SectionHead", parent=styles["Heading2"], fontSize=14, textColor=colors.HexColor(BRAND_INDIGO), spaceBefore=16, spaceAfter=8))
    styles.add(ParagraphStyle("SubHead", parent=styles["Heading3"], fontSize=11, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle("InfoMsg", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#6b7280"), spaceAfter=6))
    styles.add(ParagraphStyle("CellText", parent=styles["Normal"], fontSize=8, leading=10))

    story: list = []

    # ── Title Header ────────────────────────────────────────────────
    story.append(Spacer(1, 50))
    story.append(Paragraph(f"{BRAND} Analytics Report", styles["BrandTitle"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>File:</b> {filename}", styles["Normal"]))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now(timezone(timedelta(hours=5, minutes=30))).strftime('%B %d, %Y %H:%M IST')}", styles["Normal"]))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e7eb"), thickness=1))
    story.append(Spacer(1, 16))

    # ── 1. Dataset Summary ──────────────────────────────────────────
    summary = dataset_summary(df, filename, file_size)
    story.append(Paragraph("1. Dataset Summary", styles["SectionHead"]))
    summary_rows = [
        ["Metric", "Value"],
        ["Rows", f"{summary['rows']:,}"],
        ["Columns", str(summary["columns"])],
        ["Numeric Columns", str(summary["numeric_columns"])],
        ["Categorical Columns", str(summary["categorical_columns"])],
        ["Missing Values", f"{summary['missing_values']:,} ({summary['missing_pct']}%)"],
        ["Duplicates", f"{summary['duplicates']:,}"],
        ["Memory Usage", summary["memory_display"]],
        ["File Size", summary["file_size_display"]],
    ]
    story.append(_make_table(summary_rows))
    story.append(Spacer(1, 14))

    # ── 2. Column Analysis ──────────────────────────────────────────
    cols = column_analysis(df)
    story.append(Paragraph("2. Column Analysis", styles["SectionHead"]))
    col_rows = [["Column", "Type", "Category", "Missing", "Unique"]]
    for c in cols:
        col_rows.append([
            c["name"][:28], c["dtype"], c["category"],
            f"{c['missing']} ({c['missing_pct']}%)", str(c["unique"]),
        ])
    story.append(_make_table(col_rows))
    story.append(Spacer(1, 14))

    # ── 3. Numeric Statistics ───────────────────────────────────────
    numerics = [c for c in cols if c["category"] == "numeric"]
    categoricals = [c for c in cols if c["category"] == "categorical"]

    if numerics:
        story.append(Paragraph("3. Numeric Column Statistics", styles["SectionHead"]))
        num_rows = [["Column", "Mean", "Median", "Std", "Skew", "Min", "Max"]]
        for c in numerics:
            s = c.get("stats", {})
            num_rows.append([
                c["name"][:20],
                f"{s.get('mean', 0):.2f}", f"{s.get('median', 0):.2f}",
                f"{s.get('std', 0):.2f}", f"{s.get('skew', 0):.2f}",
                f"{s.get('min', 0):.2f}", f"{s.get('max', 0):.2f}",
            ])
        story.append(_make_table(num_rows))
        story.append(Spacer(1, 14))
    else:
        story.append(Paragraph("3. Numeric Column Statistics", styles["SectionHead"]))
        story.append(Paragraph("No numeric columns found in this dataset.", styles["InfoMsg"]))

    # ── 4. Distribution Charts ──────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("4. Distribution Charts", styles["SectionHead"]))

    if numerics:
        for c in numerics[:4]:
            try:
                series = df[c["name"]].dropna()
                if len(series) > 0:
                    story.append(Paragraph(f"<b>{c['name']}</b>", styles["SubHead"]))
                    story.append(_draw_histogram(df[c["name"]], c["name"]))
                    story.append(Spacer(1, 10))
            except Exception as e:
                logger.warning("Histogram for %s failed: %s", c["name"], e)
    else:
        story.append(Paragraph("No numeric columns available for distribution charts.", styles["InfoMsg"]))

    if categoricals:
        for c in categoricals[:3]:
            top_vals = c.get("top_values", [])[:8]
            if top_vals:
                labels = [v["value"] for v in top_vals]
                counts = [v["count"] for v in top_vals]
                try:
                    story.append(Paragraph(f"<b>{c['name']}</b>", styles["SubHead"]))
                    story.append(_draw_bar_chart(labels, counts, c["name"]))
                    story.append(Spacer(1, 10))
                except Exception as e:
                    logger.warning("Bar chart for %s failed: %s", c["name"], e)

    # pie chart for first categorical with ≤ 8 unique values
    pie_candidates = [c for c in categoricals if c["unique"] <= 8 and c.get("top_values")]
    if pie_candidates:
        c = pie_candidates[0]
        vals = c["top_values"][:8]
        try:
            story.append(Paragraph(f"<b>{c['name']}</b> — Pie Chart", styles["SubHead"]))
            story.append(_draw_pie([v["value"] for v in vals], [v["count"] for v in vals], c["name"]))
            story.append(Spacer(1, 10))
        except Exception as e:
            logger.warning("Pie chart for %s failed: %s", c["name"], e)

    # ── 5. Correlation Analysis ─────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("5. Correlation Analysis", styles["SectionHead"]))

    corr = correlation_matrix(df)
    if corr.get("message") and len(corr["columns"]) < 2:
        story.append(Paragraph(corr["message"], styles["InfoMsg"]))
    else:
        # heatmap image
        try:
            story.append(_draw_heatmap(corr))
            story.append(Spacer(1, 12))
        except Exception as e:
            logger.warning("Heatmap failed: %s", e)

        # top correlations table
        pairs = _top_correlations(corr, top_n=10)
        if pairs:
            story.append(Paragraph("Top Correlation Pairs", styles["SubHead"]))
            pair_rows = [["Column A", "Column B", "Correlation"]]
            for a, b, v in pairs:
                pair_rows.append([a, b, f"{v:.3f}"])
            story.append(_make_table(pair_rows))
            story.append(Spacer(1, 14))

    # ── 6. Scatter Plots ────────────────────────────────────────────
    num_col_names = [c["name"] for c in numerics]
    if len(num_col_names) >= 2:
        story.append(Paragraph("6. Scatter Plots", styles["SectionHead"]))
        # pick top correlated pairs for scatter plots
        scatter_pairs = _top_correlations(corr, top_n=3) if len(corr["columns"]) >= 2 else []
        if not scatter_pairs and len(num_col_names) >= 2:
            scatter_pairs = [(num_col_names[0], num_col_names[1], 0)]
        for col_a, col_b, _ in scatter_pairs[:3]:
            try:
                story.append(Paragraph(f"<b>{col_a}</b> vs <b>{col_b}</b>", styles["SubHead"]))
                story.append(_draw_scatter(df, col_a, col_b))
                story.append(Spacer(1, 10))
            except Exception as e:
                logger.warning("Scatter for %s vs %s failed: %s", col_a, col_b, e)
    else:
        story.append(Paragraph("6. Scatter Plots", styles["SectionHead"]))
        story.append(Paragraph("Scatter plots require at least 2 numeric columns. This dataset does not meet that requirement.", styles["InfoMsg"]))

    # ── 7. Box Plots ────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("7. Box Plots", styles["SectionHead"]))
    if numerics:
        bp_cols = num_col_names[:6]
        try:
            story.append(_draw_boxplot(df, bp_cols))
            story.append(Spacer(1, 14))
        except Exception as e:
            logger.warning("Boxplot failed: %s", e)
    else:
        story.append(Paragraph("No numeric columns available for box plot analysis.", styles["InfoMsg"]))

    # ── 8. Outlier Detection ────────────────────────────────────────
    story.append(Paragraph("8. Outlier Detection (IQR Method)", styles["SectionHead"]))
    if numerics:
        out_rows = [["Column", "Outliers", "% of Data", "Lower Fence", "Upper Fence"]]
        for c in numerics[:10]:
            od = outlier_detection(df, c["name"])
            if od.get("error"):
                continue
            out_rows.append([
                c["name"][:20], str(od.get("outlier_count", 0)),
                f"{od.get('outlier_pct', 0)}%",
                f"{od.get('lower_fence', 0):.2f}", f"{od.get('upper_fence', 0):.2f}",
            ])
        if len(out_rows) > 1:
            story.append(_make_table(out_rows))
        else:
            story.append(Paragraph("No outlier data could be computed.", styles["InfoMsg"]))
    else:
        story.append(Paragraph("No numeric columns available for outlier detection.", styles["InfoMsg"]))
    story.append(Spacer(1, 14))

    # ── 9. Categorical Insights ─────────────────────────────────────
    if categoricals:
        story.append(Paragraph("9. Categorical Columns — Top Values", styles["SectionHead"]))
        for c in categoricals[:6]:
            story.append(Paragraph(f"<b>{c['name']}</b> ({c['unique']} unique values)", styles["SubHead"]))
            tv = c.get("top_values", [])[:5]
            cat_rows = [["Value", "Count"]]
            for item in tv:
                cat_rows.append([item["value"][:35], str(item["count"])])
            story.append(_make_table(cat_rows, col_widths=[3.5 * inch, 1.5 * inch]))
            story.append(Spacer(1, 6))

    doc.build(story, onFirstPage=_watermark, onLaterPages=_watermark)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Table helper
# ---------------------------------------------------------------------------

def _make_table(data, col_widths=None):
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(BRAND_PURPLE)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]
    t.setStyle(TableStyle(style))
    return t


def _top_correlations(corr: dict, top_n: int = 10):
    cols = corr["columns"]
    matrix = corr["matrix"]
    pairs = []
    for i in range(len(cols)):
        for j in range(i + 1, len(cols)):
            pairs.append((cols[i], cols[j], abs(matrix[i][j])))
    pairs.sort(key=lambda x: x[2], reverse=True)
    return [(a, b, v) for a, b, v in pairs[:top_n]]
